Repository predictionmachine/pm-github-actions, pull requests merged in 2021-05, with the labels that each got.

#30 drop unused env var in `pm-gh-actions.yml`
  .github/workflows/pm-gh-actions.yml
Labels: enhancement

#32 Add branch name check in pm-gh-action & some refactor
  .github/workflows/pm-gh-actions.yml
  README.md
Labels: enhancement

#33 Fix coverage in pm-gh-actions
  .github/pull_request_template.md
  .github/workflows/pm-gh-actions.yml
  pyproject.toml
  setup.cfg
Labels: bug

#34 Remove unit test results from workflow and update the readme for the same
  .github/workflows/pm-gh-actions.yml
  README.md
Labels: enhancement

#36 call out need to configure mypy
  README.md
Labels: documentation

#37 wording changes to "check branch name" step
  .github/workflows/pm-gh-actions.yml
Labels: enhancement

#41 small updates to pyproject, readme, interrogate call
  .github/workflows/pm-gh-actions.yml
  README.md
  pyproject.toml
  requirements-dev.txt
Labels: enhancement

#38 add `.codeclimate.yml` config file
  .codeclimate.yml
  .github/pull_request_template.md
  .github/workflows/pm-gh-actions.yml
  README.md
  pyproject.toml
Labels: enhancement

#43 update `.codeclimate.yml` plugins and updae`README.md` for code climate configuration file
  .codeclimate.yml
  README.md
Labels: documentation, enhancement

#44 launch pytest with `python -m pytest`
  .github/workflows/pm-gh-actions.yml
  setup.cfg
Labels: bug

#45 fix links to repo after repo rename to `pm-github-actions`
  README.md
Labels: documentation

#46 fix links to repo, fix running and formatting of `interrogate` report
  .github/workflows/pm-gh-actions.yml
  README.md
Labels: bug, documentation
