Repository predictionmachine/pm-github-actions, pull requests merged in 2021-06, with the labels that each got.

#47 add timeouts, pre-commit config file
  .github/workflows/pm-gh-actions.yml
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: enhancement

#48 Update README.md for pre-commit
  README.md
Labels: documentation

#49 add flake8 to pre-commit config and required mypy version
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: enhancement

#50 update pre-commit-config to 0.1.3 and requirements-dev to 0.1.4
  .pre-commit-config.yaml
  requirements-dev.txt
Labels: enhancement

#51 Fix `mypy` CI step
  .github/workflows/pm-gh-actions.yml
Labels: bug

#52 install dependencies so mypy CI works
  .github/workflows/pm-gh-actions.yml
Labels: bug

#53 Move mypy config to `pyproject.toml` , update action file for mypy step & file versions
  .github/workflows/pm-gh-actions.yml
  README.md
  projectname/__init__.py
  pyproject.toml
  setup.cfg
  tests/__init__.py
  tests/projectname/__init__.py
Labels: documentation, enhancement

#54 Remove coverage config from setup.cfg & update coverage action step
  .github/workflows/pm-gh-actions.yml
  setup.cfg
Labels: enhancement
